import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class LieuxService {
  constructor() {}
  gouvernorats = [
    'Ariana',
    'Béja',
    'Ben Arous',
    'Bizerte',
    'Gabès',
    'Gafsa',
    'Jendouba',
    'Kairouan',
    'Kasserine',
    'Kébili',
    'Le Kef',
    'Mahdia',
    'La Manouba',
    'Médenine',
    'Monastir',
    'Nabeul',
    'Sfax',
    'Sidi Bouzid',
    'Siliana',
    'Sousse',
    'Tataouine',
    'Tozeur',
    'Tunis',
    'Zaghouan',
  ];

  muncipalites = [
    [
      'Ariana Ville',
      'Ettadhamen',
      'Kalâat el-Andalous',
      'La Soukra',
      'Mnihla',
      'Raoued',
      'Sidi Thabet',
    ],
    [
      'Amdoun',
      'Béja Nord',
      'Béja Sud',
      'Goubellat',
      'Medjez el-Bab',
      'Nefza',
      'Téboursouk',
      'Testour',
      'Thibar',
    ],
    [
      'Ben Arous',
      'Bou Mhel el-Bassatine',
      'El Mourouj',
      'Ezzahra',
      'Fouchana',
      'Hammam Chott',
      'Hammam Lif',
      'Mohamedia',
      'Medina Jedida',
      'Mégrine',
      'Mornag',
      'Radès',
    ],
    [
      'Bizerte Nord',
      'Bizerte Sud',
      'El Alia',
      'Ghar El Melh',
      'Ghezala',
      'Joumine',
      'Mateur',
      'Menzel Bourguiba',
      'Menzel Jemil',
      'Ras Jebel',
      'Sejnane',
      'Tinja',
      'Utique',
      'Zarzouna',
    ],
    [
      'Gabès Médina',
      'Gabès Ouest ',
      'Gabès Sud',
      'Ghannouch',
      'El Hamma',
      'Matmata',
      'Mareth',
      'Menzel',
      'Métouia',
      'Nouvelle Matmata',
    ],
    [
      'Belkhir',
      'El Guettar ',
      'El Ksar',
      'Gafsa Nord',
      'Gafsa Sud',
      'Mdhilla',
      'Métlaoui',
      'Moularès',
      'Redeyef',
      'Sened',
      'Sidi Aïch',
    ],
    [
      'Aïn Draham',
      'Balta-Bou Aouane',
      'Bou Salem',
      'Fernana',
      'Ghardimaou',
      'Jendouba Sud',
      'Jendouba Nord',
      'Oued Meliz',
      'Tabarka',
    ],

    [
      'Bou Hajla',
      'Chebika',
      'Echrarda',
      'El Alâa',
      'Haffouz',
      'Hajeb El Ayoun',
      'Kairouan Nord',
      'Kairouan Sud',
      'Nasrallah',
      'Oueslatia',
      'Sbikha',
    ],
    [
      'El Ayoun',
      'Ezzouhour',
      'Fériana',
      'Foussana',
      'Haïdra',
      'Hassi El Ferid',
      'Jedelienne',
      'Kasserine Nord',
      'Kasserine Sud',
      'Majel Bel Abbès',
      'Sbeïtla',
      'Sbiba',
      'Thala',
    ],
    [
      'Douz Nord',
      'Douz Sud',
      'Faouar',
      'Kébili Nord',
      'Kébili Sud',
      'Souk Lahad',
    ],
    [
      'Borj El Amri',
      'Djedeida',
      'Douar Hicher',
      'El Batan',
      'La Manouba',
      'Mornaguia',
      'Oued Ellil',
      'Tebourba',
    ],
    [
      'Dahmani',
      'Jérissa',
      'El Ksour',
      'Sers',
      'Kalâat Khasba',
      'Kalaat Senan',
      'Kef Est',
      'Kef Ouest',
      'Nebeur',
      'Sakiet Sidi Youssef',
      'Tajerouine',
    ],
    [
      'Bou Merdes',
      'Chebba',
      'Chorbane',
      'El Jem',
      'Essouassi',
      'Hebira',
      'Ksour Essef',
      'Mahdia',
      'Melloulèche',
      'Ouled Chamekh',
      'Sidi Alouane',
    ],
    [
      'Ben Gardane',
      'Beni Khedache',
      'Djerba - Ajim',
      'Djerba - Houmt Souk',
      'Djerba - Midoun',
      'Médenine Nord',
      'Médenine Sud',
      'Sidi Makhlouf',
      'Zarzis',
    ],
    [
      'Bekalta',
      'Bembla',
      'Beni Hassen',
      'Jemmal',
      'Ksar Hellal',
      'Ksibet el-Médiouni',
      'Moknine',
      'Monastir',
      'Ouerdanine',
      'Sahline',
      'Sayada-Lamta-Bou Hajar',
      'Téboulba',
      'Zéramdine',
    ],
    [
      'Béni Khalled',
      'Béni Khiar',
      'Bou Argoub',
      'Dar Chaâbane El Fehri',
      'El Haouaria',
      'El Mida',
      'Grombalia',
      'Hammam Ghezèze',
      'Hammamet',
      'Kélibia',
      'Korba',
      'Menzel Bouzelfa',
      'Menzel Temime',
      'Nabeul',
      'Soliman',
      'Takelsa',
    ],
    [
      'Agareb',
      'Bir Ali Ben Khalifa',
      'El Amra',
      'El Hencha',
      'Graïba',
      'Jebiniana',
      'Kerkennah',
      'Mahrès',
      'Menzel Chaker',
      'Sakiet Eddaïer',
      'Sakiet Ezzit',
      'Sfax Ouest',
      'Sfax Sud',
      'Sfax Ville',
      'Skhira',
      'Thyna',
    ],
    [
      'Bir El Hafey',
      'Cebbala Ouled Asker',
      'Jilma',
      'Meknassy',
      'Menzel Bouzaiane',
      'Mezzouna',
      'Ouled Haffouz',
      'Regueb',
      'Sidi Ali Ben Aoun',
      'Sidi Bouzid Est',
      'Sidi Bouzid Ouest',
      'Souk Jedid',
    ],
    [
      'Bargou',
      'Bou Arada',
      'El Aroussa',
      'El Krib',
      'Gaâfour',
      'Kesra',
      'Makthar',
      'Rouhia',
      'Sidi Bou Rouis',
      'Siliana Nord',
      'Siliana Sud',
    ],
    [
      'Akouda',
      'Bouficha',
      'Chott Meriem',
      'Enfida',
      'Hammam Sousse',
      'Hergla',
      'Kalâa Kebira',
      'Kalâa Seghira',
      'Kondar',
      'M\'saken',
      'Sidi Bou Ali',
      'Sidi El Hani',
      'Sousse Jawhara',
      'Sousse Médina',
      'Sousse Riadh',
      'Sousse Sidi Abdelhamid',
    ],
    [
      'Bir Lahmar',
      'Dehiba',
      'Ghomrassen',
      'Remada',
      'Smâr',
      'Tataouine Nord',
      'Tataouine Sud',
    ],
    ['Degache', 'Hazoua', 'Nefta', 'Tameghza', 'Tozeur'],
    [
      'Bab El Bhar',
      'Bab Souika',
      'Carthage',
      'Cité El Khadra',
      'Djebel Jelloud',
      'El Kabaria',
      'El Menzah',
      'El Omrane',
      'El Omrane supérieur',
      'El Ouardia',
      'Ettahrir',
      'Ezzouhour',
      'Hraïria',
      'La Goulette',
      'La Marsa',
      'Le Bardo',
      'Le Kram',
      'Médina',
      'Séjoumi',
      'Sidi El Béchir',
      'Sidi Hassine',
    ],
    ['Bir Mcherga', 'El Fahs', 'Nadhour', 'Saouaf', 'Zaghouan', 'Zriba'],
  ];
  getGouvernorats() {
    return this.gouvernorats;
  }
  getMunicipalite() {
    return this.muncipalites;
  }
}
